// ================================================================
//  TEXTES DE L'INTERFACE — français, anglais, allemand
// ================================================================
Object.assign(I18N.fr, {
  brand_sub: "Simulateur de traction par kite · Léman", nav_home: "Accueil", nav_sandbox: "Bac à sable", nav_beginner: "Traversée débutant", nav_expert: "Traversée expert",
  help: "Aide", board: "Classements", tutorial: "Tutoriel", play: "Jouer", explore: "Explorer", next: "Suivant ▶", back: "◀ Retour", got_it: "Compris ⏎", lets_go: "C'est parti ⏎",
  cancel: "Annuler", close: "Fermer", home: "Accueil", play_again: "Rejouer ⏎", pause: "Pause", resume: "Reprendre", quit: "Quitter", key_space: "Espace", key_esc: "Échap", u_kn: "nd",
  hero_title: "Pilote un <em>kite de traction</em> sur le Léman", hero_text: "Une barge à gravier de 40 m, un kite de 150 m² et le même vent pour tout le monde : de Villeneuve au Jet d'eau, au lever puis au coucher du soleil.",
  play_beginner: "▶ Traversée débutant", play_expert: "▶ Traversée expert",
  vision_title: "La vision du jeu",
  vision_html: "<p><b>Æther Swiss Kite Simulator</b> te met à la barre d'une barge à gravier tractée par un kite. Le jeu s'appuie sur une physique crédible : traction dans la fenêtre de vol, vent apparent, inertie d'une barge chargée, effet des risées et des tempêtes.</p><ul><li><b>Comprendre</b> comment un kite tire un bateau, et pourquoi il faut voler en 8.</li><li><b>Voir</b> que ralentir (slow steaming) reste le premier levier pour réduire les émissions, et ce que le vent ajoute.</li><li><b>S'affronter</b> sur la même traversée, avec la même météo pour tous, et comparer ses temps en équipe.</li></ul>",
  card_sandbox_tag: "Comprendre · sans chrono", card_sandbox_desc: "La barge vue de travers : règle vitesse, cap et vent, et observe d'où viennent les économies de carburant. Le slow steaming expliqué simplement.",
  card_beginner_tag: "≈ 1 min · ados et grand public", card_beginner_desc: "Pilote la barge (ZQSD ou souris), sors le kite au bon moment et attrape les risées. Le kite vole tout seul en 8 : à toi de choisir la route.",
  card_expert_tag: "≈ 3 min · ingénieurs", card_expert_desc: "Pilote toi-même le kite avec les flèches : lignes arrière pour virer, lignes avant pour choquer ou border. Joue avec les limites de la fenêtre de vol.",
  hud_ship: "Barge", hud_true_wind: "Vent réel", hud_app_wind: "Vent apparent", hud_kite_pull: "Traction kite",
  top_view: "02 Vue du dessus", leg_heading: "Cap", leg_true: "Vent réel", leg_app: "Vent apparent", leg_kite: "Traction kite",
  gains_title: "03 Gains <b>vs 8 nd sans kite</b>", g_fuel: "Carburant", g_co2: "CO₂ évité", g_kite: "Poussée kite",
  k_fuel: "Gazole / traversée", k_co2: "CO₂ / traversée", k_time: "Durée", k_power: "Puissance",
  controls_title: "04 Commandes <b>· potards, clavier ou molette</b>", kite_deployed: "Kite déployé", to_toggle: "pour basculer",
  preset_ref: "Référence", preset_slow: "Slow steaming", preset_ideal: "Vent idéal", preset_storm: "Bise de face",
  ana_where: "05 D'où viennent les économies", ana_emissions: "Émissions · 100 % = référence", ana_split: "Répartition du gain", ana_curve: "06 CO₂ de la traversée selon la vitesse", ana_cube: "07 Loi du cube",
  cube_note: "Puissance ∝ V³ : gazole par traversée (coque seule, sans vent).",
  kn_speed: "Vitesse", kn_heading: "Cap", kn_winddir: "Vent du", kn_windspeed: "Force du vent",
  mission_n: "Mission {n}/{m}", m_toast: "Mission {n} réussie ✓", m_done: "✓ Réussie", m_already: "Déjà réussie", m_running: "En cours",
  m1_title: "Le kite seul", m1_text: "Sans ralentir (≥ 7,9 nœuds), joue sur le cap et le vent pour éviter au moins 15 % de CO₂ grâce au kite.",
  m2_title: "Ralentir", m2_text: "Même météo, baisse la vitesse : divise les émissions de la traversée par deux (≥ 50 % de CO₂ évité).",
  m3_title: "Bise de face", m3_text: "Vent de face à 22 nœuds : le kite ne peut rien. Trouve quand même 30 % d'économies.",
  m4_title: "Le bon compromis", m4_text: "Arrive à Genève en moins de 6 h tout en évitant au moins 55 % de CO₂ : combine vitesse, cap et vent.",
  delta_ref: "= référence", st_flying: "Kite en vol · trajectoire en 8", st_off: "Kite rentré", st_calm: "Kite au repos · pas assez de vent", st_storm: "Kite rentré · vent trop fort", st_headwind: "Kite inutile · vent de face",
  st_off_short: "kite rentré", st_calm_short: "pas assez de vent", st_storm_short: "vent trop fort", st_headwind_short: "vent de face",
  big_zero: "0 % de CO₂", big_less: "−{p} % CO₂", big_more: "+{p} % CO₂", sub_saved: "{t} kg évités sur {r} kg", sub_more: "{t} kg en plus sur {r} kg",
  seg_emitted: "{p} % émis", seg_speed: "−{p} % vitesse", seg_kite: "−{p} % kite", rest_emitted: "{t} kg émis", share_speed: "Vitesse {p} %", share_kite: "Kite {p} %", split_txt: "{s} % vitesse · {k} % kite", no_gain: "aucun gain",
  ins_faster: "<b>Plus vite que la référence.</b> La puissance croît comme le <b>cube</b> de la vitesse : +{p} % de puissance pour +{v} % de vitesse.",
  ins_nogain: "<b>Pas encore d'économies.</b> Deux leviers : <b>baisser la vitesse</b> (toujours efficace) ou trouver un <b>vent portant</b> pour le kite.",
  ins_main: "<b>{s} % du gain vient du ralentissement</b>, {k} % du kite. ",
  ins_speed_main: "À {v} nd, le moteur fournit {p} % de la puissance de référence ; chaque kilomètre coûte {f} % du gazole.",
  ins_not_slowed: "Tu n'as pas encore ralenti : à 6–7 nœuds, le gain serait bien plus grand, et <b>garanti</b> quelle que soit la météo.",
  ins_wind_fav: "Vent très favorable… mais ce gain dépend de la météo, alors que celui du ralentissement est <b>garanti</b>.",
  ins_kite_none: "Le kite n'apporte rien ici : tout vient du ralentissement.",
  g1_sub: "{t} kg de gazole {dir}", less: "en moins", more: "en plus", g2_sub: "≈ {n} km en voiture", g3_sub: "{p} % de la poussée",
  c_ref: "référence", c_nokite: "sans kite", c_kite: "avec kite", c_gain: "apport kite",
  d_time: "Chrono", d_progress: "Progression", d_speed: "Vitesse", d_engine: "Moteur", d_wind: "Vent", d_kite: "Kite", d_kite_bar: "Kite tension · utile", rig_area: "Surface", rig_line: "Lignes", rig_locked: "Rentre le kite pour changer de surface ou de lignes", e_rig: "Gréement", d_share: "Part kite", d_perf: "Fluidité", d_avoided: "évité", d_gust: "risée", d_storm: "tempête", d_co2: "CO₂ émis", d_saved: "CO₂ évité (kite)", d_heel: "Gîte", d_pen: "Pénalités",
  start_name: "VILLENEUVE", finish_name: "GENÈVE", t_ghost: "Traces top 3", t_window: "Fenêtre", throttle: "Gaz", helm: "Barre", kite: "Kite",
  kb_tension: "Tension", kb_trim: "Puissance", kb_zone: "Zone", kite_deploy: "Sortir le kite", kite_retract: "Rentrer le kite",
  ks_stowed: "rentré", ks_calm: "pétole", ks_headwind: "vent de face", ks_launch: "décollage", ks_crashed: "à l'eau",
  view_third: "3e personne", view_cabin: "Cabine", go: "Top !",
  name_eyebrow: "{mode} · Villeneuve → Genève", name_title: "Qui est à la <em>barre</em> ?", name_intro: "Ton pseudo et ton équipe apparaîtront dans les classements de tous les joueurs.",
  pseudo: "Pseudo", pseudo_ph: "Ton pseudo", team: "Équipe", team_new_name: "Nom de la nouvelle équipe", team_ph: "Ex. Les Mouettes",
  team_none: "— Sans équipe —", team_members: "{t} · {n} membre(s)", team_create: "＋ Créer une nouvelle équipe…", err_name: "Écris un pseudo pour enregistrer ton temps.", err_team: "Donne un nom à ta nouvelle équipe (ou choisis « Sans équipe »).",
  pause_title: "Tout est <em>figé</em>", pause_text: "Appuie sur <kbd>P</kbd> ou <kbd>Échap</kbd> pour reprendre.",
  race_abandoned: "Traversée abandonnée",
  w_vaudaire: "La Vaudaire souffle du sud-est : vent dans le dos, sors le kite !", w_vent: "Le « Vent » du sud-ouest arrive de face : le kite tire peu, garde de la vitesse au moteur.",
  w_joran: "Coup de Joran ! Le vent du nord-ouest forcit brutalement.", w_bise: "La Bise du nord-est te pousse vers Genève : c'est le moment d'attraper les risées.",
  storm_warn: "⚠ Tempête de Joran droit devant : rentre le kite (Espace) si la tension monte !", storm_warn_expert: "⚠ Tempête de Joran : choque les lignes avant (↑) et sors de la zone de puissance.",
  dolphins: "🐬 Des dauphins t'accompagnent !", gust_caught: "Risée attrapée ! 💨",
  ev_kite_torn: "💥 Rafale trop forte : le kite est endommagé", ev_line_break: "💥 Surcharge : la ligne a cassé", ev_kite_water: "🌊 Le kite a touché l'eau",
  ev_aground: "Échouage sur la rive !", ev_cgn: "💥 Collision avec un vapeur de la CGN", ev_jetski: "Accrochage avec un jet-ski",
  kite_damaged_wait: "Kite en réparation, patiente quelques secondes…", kite_out: "Kite sorti 🪁", kite_in: "Kite rentré",
  overload: "SURCHARGE", overload_hint: "rentre le kite (Espace) avant qu'il se déchire", overload_hint_expert: "choque (↑) ou sors de la zone de puissance",
  no_ghosts: "Pas encore de traces : sois le premier à les tracer !",
  start_tip: "ZQSD ou flèches pour piloter, Espace pour sortir le kite. Cap sur Genève !", start_tip_expert: "ZQSD pour la barge, flèches pour le kite : fais des 8 dans la zone de puissance.",
  finish_toast: "Arrivée au Jet d'eau ! {t}",
  win_power: "ZONE DE PUISSANCE", win_edge: "BORD", win_zenith: "ZÉNITH",
  boards: "Classements", src_remote: "tous les joueurs", src_local: "ce navigateur", p_day: "Jour", p_week: "Semaine", p_all: "Historique", g_players: "Joueurs", g_teams: "Équipes",
  best_time: "Meilleur temps", runs: "Courses", avg_time: "Temps moyen", members: "Membres", no_scores: "Aucun temps pour l'instant : sois le premier !", no_teams: "Aucune équipe pour l'instant.",
  runs_count: "{n} course(s) · meilleur temps de chaque joueur", team_rule: "Temps d'équipe = moyenne des meilleurs temps de ses membres", dist_note: "Répartition des meilleurs temps", dist_empty: "Pas encore assez de joueurs", you: "toi",
  end_eyebrow: "Arrivée · {mode}", end_title_1: "Nouveau <em>record</em> ! 🏆", end_title_podium: "Sur le <em>podium</em> ! 🥇", end_title: "Arrivée au <em>Jet d'eau</em>",
  e_time: "Temps de course", e_pen: "Pénalités", e_coll: "collision(s)", e_co2: "CO₂ émis par le moteur", e_saved: "CO₂ évité grâce au kite", end_rank: "Rang {r} sur {n} joueurs (historique)", speed_scale: "vitesse le long de ta route",
  read_title: "Ce que tu vois <em>à l'écran</em>",
  hs_title: "Bac à sable : <em>explore</em> librement", hs_text: "La barge est vue de travers. Règle la vitesse, le cap et le vent, et regarde d'où viennent les économies : en général, ralentir rapporte environ deux tiers du gain, le kite le reste.",
  k_sb_speed: "Vitesse de la barge ±0,5 nœud", k_sb_heading: "Cap ±5°", k_sb_kite: "Déployer / rentrer le kite", k_sb_knobs: "Tourner les potards (glisser ou molette)",
  rs_hud: "<b>Étiquettes en haut</b> : vitesse et cap, vent réel, vent apparent, traction du kite.", rs_mission: "<b>Mission</b> (en bas à droite) : un objectif qui passe au vert une fois réussi.",
  rs_compass: "<b>02 Boussole</b> : cap (vert), vent réel (bleu), vent apparent (pointillés), traction du kite (orange).", rs_gauges: "<b>03 Jauges</b> : gazole et CO₂ économisés par rapport à la référence (8 nœuds, sans kite).",
  rs_bars: "<b>05 Barres</b> : quelle part du gain vient du ralentissement et quelle part vient du kite.", rs_curves: "<b>06–07</b> : CO₂ de la traversée selon la vitesse et loi du cube.",
  hb_title: "Traverse le Léman <em>le plus vite possible</em>", hb_text: "Départ du quai de gravier de Villeneuve, arrivée au pied du Jet d'eau à Genève. Ton temps est précis au millième : chaque risée compte !",
  hb_r1_t: "Objectif", hb_r1_d: "Le meilleur temps. Les collisions (bateaux CGN +5 s, jet-skis +2 s, rives +1,5 s) s'ajoutent au chrono.",
  hb_r2_t: "Le kite", hb_r2_d: "Il vole tout seul en 8. Sors-le quand le vent vient de l'arrière ou du travers, et va chercher les risées (taches sombres).",
  hb_r3_t: "Danger", hb_r3_d: "Le Joran forcit d'un coup au milieu du lac : rentre le kite si la tension passe au rouge, sinon il se déchire (+4 s).",
  he_title: "Pilote le kite <em>comme un pro</em>", he_text: "Même traversée, mais c'est toi qui fais voler l'aile. Elle avance seule dans la fenêtre de vol ; tu la fais virer et tu règles sa puissance. Avant de sortir le kite, choisis sa surface (10, 25 ou 100 m²) et ses lignes (25, 100 ou 300 m) : petit = vif mais faible, grand = puissant mais lent ; lignes longues = plus de vent en altitude, virages plus lents.",
  he_r1_t: "Fenêtre de vol", he_r1_d: "Au centre et bas : puissance maximale. Au bord et au zénith : presque rien. En 8, l'aile crée son propre vent et tire bien plus fort.",
  he_r2_t: "Lignes avant", he_r2_d: "↑ choquer = moins de puissance, ↓ border = plus de puissance. Trop de tension et la ligne casse (+3 s) : la limite dépend de la taille du kite.",
  he_r3_t: "Lignes arrière", he_r3_d: "← → font virer l'aile. Elle tourne plus vite quand elle est rapide. Si elle touche l'eau : +2 s et relance.",
  ctrl_title: "Commandes", k_throttle: "Gaz : accélérer / ralentir (reste en position)", k_helm: "Barre : bâbord / tribord", k_kite_steer: "Kite : virer à gauche / à droite (lignes arrière)",
  k_kite_trim: "Kite : ↑ choquer / ↓ border (lignes avant)", k_arrows_boat: "Les flèches pilotent aussi la barge", k_kite_toggle: "Sortir / rentrer le kite", k_view: "Vue 3e personne / cabine", k_window: "Afficher la fenêtre de vol",
  k_ghost: "Traces des 3 meilleurs joueurs", k_help: "Afficher l'aide", k_pause: "Pause",
  ctrl_mouse: "À la souris : manette des gaz à gauche de la scène, barre de direction en bas (double-clic pour la remettre droite), bouton du kite en bas à droite.",
  ctrl_qwerty: "Clavier QWERTY : W A S D fonctionnent aussi.",
  rr_hud: "<b>En haut à gauche</b> : chrono, vitesse, vent (force et provenance), poussée utile du kite.", rr_progress: "<b>En haut au centre</b> : progression de Villeneuve à Genève.",
  rr_minimap: "<b>Mini-carte</b> : ta position, les risées (points colorés), la zone de tempête (rouge) et les vapeurs CGN (points blancs).",
  rr_wind: "<b>Traits sur l'eau</b> : le vent, coloré de bleu (faible) à rouge et violet (fort) ; taches sombres = risées, plaques claires = pétole.",
  rr_kitebox: "<b>Encadré du kite</b> : tension de ligne (rouge = danger), zone de vol, puissance réglée.", rr_databar: "<b>Barre du bas</b> : moteur, CO₂ émis et évité, gîte, pénalités, images par seconde.",
  rr_beginner: "Astuce : le moteur seul plafonne vers 8,5 nœuds ; le kite bien placé t'en donne 2 à 4 de plus.", rr_expert: "Astuce : en plein centre et à pleine puissance, la ligne casse vite. Joue avec le bord de la fenêtre et choque dans les rafales."
});

Object.assign(I18N.en, {
  brand_sub: "Kite traction simulator · Lake Geneva", nav_home: "Home", nav_sandbox: "Sandbox", nav_beginner: "Beginner crossing", nav_expert: "Expert crossing",
  help: "Help", board: "Leaderboards", tutorial: "Tutorial", play: "Play", explore: "Explore", next: "Next ▶", back: "◀ Back", got_it: "Got it ⏎", lets_go: "Let's go ⏎",
  cancel: "Cancel", close: "Close", home: "Home", play_again: "Play again ⏎", pause: "Pause", resume: "Resume", quit: "Quit", key_space: "Space", key_esc: "Esc", u_kn: "kn",
  hero_title: "Fly a <em>traction kite</em> on Lake Geneva", hero_text: "A 40 m gravel barge, a 150 m² kite and the same wind for everyone: from Villeneuve to the Jet d'eau, from sunrise to sunset.",
  play_beginner: "▶ Beginner crossing", play_expert: "▶ Expert crossing",
  vision_title: "The idea behind the game",
  vision_html: "<p><b>Æther Swiss Kite Simulator</b> puts you at the helm of a gravel barge pulled by a kite. It runs on credible physics: traction inside the wind window, apparent wind, the inertia of a loaded barge, gusts and storms.</p><ul><li><b>Understand</b> how a kite pulls a boat, and why it must fly figure-eights.</li><li><b>See</b> that slowing down (slow steaming) remains the first lever to cut emissions, and what the wind adds.</li><li><b>Compete</b> on the same crossing, with the same weather for everyone, and compare times as a team.</li></ul>",
  card_sandbox_tag: "Understand · no timer", card_sandbox_desc: "The barge seen from the side: set speed, heading and wind, and see where the fuel savings come from. Slow steaming made simple.",
  card_beginner_tag: "≈ 1 min · teens and everyone", card_beginner_desc: "Steer the barge (WASD/ZQSD or mouse), launch the kite at the right moment and catch the gusts. The kite flies figure-eights on its own: you choose the route.",
  card_expert_tag: "≈ 3 min · engineers", card_expert_desc: "Fly the kite yourself with the arrow keys: back lines to turn, front lines to depower or power up. Play with the edges of the wind window.",
  hud_ship: "Barge", hud_true_wind: "True wind", hud_app_wind: "Apparent wind", hud_kite_pull: "Kite pull",
  top_view: "02 Top view", leg_heading: "Heading", leg_true: "True wind", leg_app: "Apparent wind", leg_kite: "Kite pull",
  gains_title: "03 Gains <b>vs 8 kn without kite</b>", g_fuel: "Fuel", g_co2: "CO₂ avoided", g_kite: "Kite thrust",
  k_fuel: "Diesel / crossing", k_co2: "CO₂ / crossing", k_time: "Duration", k_power: "Power",
  controls_title: "04 Controls <b>· knobs, keyboard or wheel</b>", kite_deployed: "Kite deployed", to_toggle: "to toggle",
  preset_ref: "Reference", preset_slow: "Slow steaming", preset_ideal: "Ideal wind", preset_storm: "Bise head-on",
  ana_where: "05 Where the savings come from", ana_emissions: "Emissions · 100 % = reference", ana_split: "Share of the gain", ana_curve: "06 CO₂ per crossing vs speed", ana_cube: "07 Cube law",
  cube_note: "Power ∝ V³: diesel per crossing (hull only, no wind).",
  kn_speed: "Speed", kn_heading: "Heading", kn_winddir: "Wind from", kn_windspeed: "Wind speed",
  mission_n: "Mission {n}/{m}", m_toast: "Mission {n} complete ✓", m_done: "✓ Done", m_already: "Already done", m_running: "In progress",
  m1_title: "Kite only", m1_text: "Without slowing down (≥ 7.9 knots), use heading and wind to avoid at least 15 % CO₂ thanks to the kite.",
  m2_title: "Slow down", m2_text: "Same weather, lower the speed: halve the crossing's emissions (≥ 50 % CO₂ avoided).",
  m3_title: "Bise head-on", m3_text: "22-knot headwind: the kite is useless. Still find 30 % savings.",
  m4_title: "The right trade-off", m4_text: "Reach Geneva in under 6 h while avoiding at least 55 % CO₂: combine speed, heading and wind.",
  delta_ref: "= reference", st_flying: "Kite flying · figure-eight", st_off: "Kite stowed", st_calm: "Kite idle · not enough wind", st_storm: "Kite stowed · wind too strong", st_headwind: "Kite useless · headwind",
  st_off_short: "kite stowed", st_calm_short: "not enough wind", st_storm_short: "wind too strong", st_headwind_short: "headwind",
  big_zero: "0 % CO₂", big_less: "−{p} % CO₂", big_more: "+{p} % CO₂", sub_saved: "{t} kg avoided out of {r} kg", sub_more: "{t} kg more out of {r} kg",
  seg_emitted: "{p} % emitted", seg_speed: "−{p} % speed", seg_kite: "−{p} % kite", rest_emitted: "{t} kg emitted", share_speed: "Speed {p} %", share_kite: "Kite {p} %", split_txt: "{s} % speed · {k} % kite", no_gain: "no gain",
  ins_faster: "<b>Faster than the reference.</b> Power grows with the <b>cube</b> of speed: +{p} % power for +{v} % speed.",
  ins_nogain: "<b>No savings yet.</b> Two levers: <b>slow down</b> (always works) or find a <b>tailwind</b> for the kite.",
  ins_main: "<b>{s} % of the gain comes from slowing down</b>, {k} % from the kite. ",
  ins_speed_main: "At {v} kn the engine delivers {p} % of the reference power; each kilometre costs {f} % of the diesel.",
  ins_not_slowed: "You haven't slowed down yet: at 6–7 knots the gain would be far larger, and <b>guaranteed</b> whatever the weather.",
  ins_wind_fav: "Very favourable wind… but this gain depends on the weather, while slowing down is <b>guaranteed</b>.",
  ins_kite_none: "The kite adds nothing here: everything comes from slowing down.",
  g1_sub: "{t} kg of diesel {dir}", less: "saved", more: "extra", g2_sub: "≈ {n} km by car", g3_sub: "{p} % of the thrust",
  c_ref: "reference", c_nokite: "no kite", c_kite: "with kite", c_gain: "kite gain",
  d_time: "Time", d_progress: "Progress", d_speed: "Speed", d_engine: "Engine", d_wind: "Wind", d_kite: "Kite", d_kite_bar: "Kite pull · useful", rig_area: "Size", rig_line: "Lines", rig_locked: "Stow the kite to change size or lines", e_rig: "Rig", d_share: "Kite share", d_perf: "Smoothness", d_avoided: "avoided", d_gust: "gust", d_storm: "storm", d_co2: "CO₂ emitted", d_saved: "CO₂ avoided (kite)", d_heel: "Heel", d_pen: "Penalties",
  start_name: "VILLENEUVE", finish_name: "GENEVA", t_ghost: "Top 3 tracks", t_window: "Window", throttle: "Throttle", helm: "Helm", kite: "Kite",
  kb_tension: "Tension", kb_trim: "Power", kb_zone: "Zone", kite_deploy: "Launch kite", kite_retract: "Stow kite",
  ks_stowed: "stowed", ks_calm: "no wind", ks_headwind: "headwind", ks_launch: "launching", ks_crashed: "in the water",
  view_third: "Third person", view_cabin: "Wheelhouse", go: "Go!",
  name_eyebrow: "{mode} · Villeneuve → Geneva", name_title: "Who's at the <em>helm</em>?", name_intro: "Your name and team will appear in everyone's leaderboards.",
  pseudo: "Player name", pseudo_ph: "Your name", team: "Team", team_new_name: "New team name", team_ph: "e.g. The Seagulls",
  team_none: "— No team —", team_members: "{t} · {n} member(s)", team_create: "＋ Create a new team…", err_name: "Enter a name to record your time.", err_team: "Give your new team a name (or pick “No team”).",
  pause_title: "Everything is <em>frozen</em>", pause_text: "Press <kbd>P</kbd> or <kbd>Esc</kbd> to resume.",
  race_abandoned: "Crossing abandoned",
  w_vaudaire: "The Vaudaire blows from the south-east: wind from behind, launch the kite!", w_vent: "The south-westerly “Vent” comes head-on: the kite pulls little, keep speed with the engine.",
  w_joran: "Joran squall! The north-westerly wind picks up suddenly.", w_bise: "The north-easterly Bise pushes you towards Geneva: time to catch the gusts.",
  storm_warn: "⚠ Joran storm ahead: stow the kite (Space) if tension rises!", storm_warn_expert: "⚠ Joran storm: depower (↑) and leave the power zone.",
  dolphins: "🐬 Dolphins are joining you!", gust_caught: "Gust caught! 💨",
  ev_kite_torn: "💥 Gust too strong: the kite is damaged", ev_line_break: "💥 Overload: the line snapped", ev_kite_water: "🌊 The kite hit the water",
  ev_aground: "Ran aground!", ev_cgn: "💥 Collision with a CGN paddle steamer", ev_jetski: "Bumped into a jet ski",
  kite_damaged_wait: "Kite being repaired, wait a few seconds…", kite_out: "Kite launched 🪁", kite_in: "Kite stowed",
  overload: "OVERLOAD", overload_hint: "stow the kite (Space) before it tears", overload_hint_expert: "depower (↑) or leave the power zone",
  no_ghosts: "No tracks yet: be the first to draw them!",
  start_tip: "WASD/ZQSD or arrows to steer, Space to launch the kite. Head for Geneva!", start_tip_expert: "WASD/ZQSD for the barge, arrows for the kite: fly figure-eights in the power zone.",
  finish_toast: "Finished at the Jet d'eau! {t}",
  win_power: "POWER ZONE", win_edge: "EDGE", win_zenith: "ZENITH",
  boards: "Leaderboards", src_remote: "all players", src_local: "this browser", p_day: "Today", p_week: "This week", p_all: "All time", g_players: "Players", g_teams: "Teams",
  best_time: "Best time", runs: "Runs", avg_time: "Average time", members: "Members", no_scores: "No times yet: be the first!", no_teams: "No teams yet.",
  runs_count: "{n} run(s) · best time of each player", team_rule: "Team time = average of its members' best times", dist_note: "Distribution of best times", dist_empty: "Not enough players yet", you: "you",
  end_eyebrow: "Finish · {mode}", end_title_1: "New <em>record</em>! 🏆", end_title_podium: "On the <em>podium</em>! 🥇", end_title: "Finished at the <em>Jet d'eau</em>",
  e_time: "Race time", e_pen: "Penalties", e_coll: "collision(s)", e_co2: "CO₂ emitted by the engine", e_saved: "CO₂ avoided thanks to the kite", end_rank: "Rank {r} of {n} players (all time)", speed_scale: "speed along your route",
  read_title: "What you see <em>on screen</em>",
  hs_title: "Sandbox: <em>explore</em> freely", hs_text: "The barge is seen from the side. Set speed, heading and wind, and see where the savings come from: slowing down usually brings about two thirds of the gain, the kite the rest.",
  k_sb_speed: "Barge speed ±0.5 knot", k_sb_heading: "Heading ±5°", k_sb_kite: "Launch / stow the kite", k_sb_knobs: "Turn the knobs (drag or wheel)",
  rs_hud: "<b>Top labels</b>: speed and heading, true wind, apparent wind, kite pull.", rs_mission: "<b>Mission</b> (bottom right): a goal that turns green once achieved.",
  rs_compass: "<b>02 Compass</b>: heading (green), true wind (blue), apparent wind (dashed), kite pull (orange).", rs_gauges: "<b>03 Gauges</b>: diesel and CO₂ saved compared with the reference (8 knots, no kite).",
  rs_bars: "<b>05 Bars</b>: how much of the gain comes from slowing down and how much from the kite.", rs_curves: "<b>06–07</b>: CO₂ per crossing vs speed, and the cube law.",
  hb_title: "Cross Lake Geneva <em>as fast as you can</em>", hb_text: "Start at the Villeneuve gravel quay, finish at the foot of the Jet d'eau in Geneva. Your time is measured to the millisecond: every gust counts!",
  hb_r1_t: "Goal", hb_r1_d: "The best time. Collisions (CGN steamers +5 s, jet skis +2 s, shores +1.5 s) are added to your time.",
  hb_r2_t: "The kite", hb_r2_d: "It flies figure-eights by itself. Launch it when the wind comes from behind or abeam, and chase the gusts (dark patches).",
  hb_r3_t: "Danger", hb_r3_d: "The Joran suddenly picks up mid-lake: stow the kite if tension turns red, or it tears (+4 s).",
  he_title: "Fly the kite <em>like a pro</em>", he_text: "Same crossing, but you fly the wing. It moves on its own inside the wind window; you turn it and set its power. Before launching, pick its size (10, 25 or 100 m²) and lines (25, 100 or 300 m): small = nimble but weak, big = powerful but slow; long lines = stronger wind aloft, slower turns.",
  he_r1_t: "Wind window", he_r1_d: "Centre and low: maximum power. Edge and zenith: almost nothing. Flying figure-eights, the wing makes its own wind and pulls much harder.",
  he_r2_t: "Front lines", he_r2_d: "↑ depower = less power, ↓ power up = more power. Too much tension and the line snaps (+3 s): the limit depends on the kite size.",
  he_r3_t: "Back lines", he_r3_d: "← → turn the wing. It turns faster when it flies fast. If it hits the water: +2 s and relaunch.",
  ctrl_title: "Controls", k_throttle: "Throttle: speed up / slow down (stays in place)", k_helm: "Helm: port / starboard", k_kite_steer: "Kite: turn left / right (back lines)",
  k_kite_trim: "Kite: ↑ depower / ↓ power up (front lines)", k_arrows_boat: "Arrow keys also steer the barge", k_kite_toggle: "Launch / stow the kite", k_view: "Third person / wheelhouse view", k_window: "Show the wind window",
  k_ghost: "Tracks of the top 3 players", k_help: "Show help", k_pause: "Pause",
  ctrl_mouse: "With the mouse: throttle lever on the left of the scene, helm bar at the bottom (double-click to centre it), kite button bottom right.",
  ctrl_qwerty: "AZERTY keyboards: Z Q S D work too.",
  rr_hud: "<b>Top left</b>: time, speed, wind (strength and direction), useful kite thrust.", rr_progress: "<b>Top centre</b>: progress from Villeneuve to Geneva.",
  rr_minimap: "<b>Mini-map</b>: your position, gusts (coloured dots), the storm area (red) and CGN steamers (white dots).",
  rr_wind: "<b>Streaks on the water</b>: the wind, from blue (light) to red and purple (strong); dark patches = gusts, glassy patches = calm.",
  rr_kitebox: "<b>Kite box</b>: line tension (red = danger), wind window zone, power setting.", rr_databar: "<b>Bottom bar</b>: engine, CO₂ emitted and avoided, heel, penalties, frames per second.",
  rr_beginner: "Tip: the engine alone tops out around 8.5 knots; a well-placed kite adds 2 to 4 more.", rr_expert: "Tip: dead centre at full power, the line snaps quickly. Play with the window edge and depower in the gusts."
});

Object.assign(I18N.de, {
  brand_sub: "Zugdrachen-Simulator · Genfersee", nav_home: "Start", nav_sandbox: "Sandkasten", nav_beginner: "Überfahrt Einsteiger", nav_expert: "Überfahrt Profi",
  help: "Hilfe", board: "Ranglisten", tutorial: "Anleitung", play: "Spielen", explore: "Entdecken", next: "Weiter ▶", back: "◀ Zurück", got_it: "Verstanden ⏎", lets_go: "Los geht's ⏎",
  cancel: "Abbrechen", close: "Schliessen", home: "Start", play_again: "Nochmal ⏎", pause: "Pause", resume: "Weiter", quit: "Beenden", key_space: "Leertaste", key_esc: "Esc", u_kn: "kn",
  hero_title: "Steuere einen <em>Zugdrachen</em> auf dem Genfersee", hero_text: "Ein 40 m langes Kiesschiff, ein 150 m² grosser Kite und derselbe Wind für alle: von Villeneuve bis zum Jet d'eau, von Sonnenaufgang bis Sonnenuntergang.",
  play_beginner: "▶ Überfahrt Einsteiger", play_expert: "▶ Überfahrt Profi",
  vision_title: "Die Idee des Spiels",
  vision_html: "<p><b>Æther Swiss Kite Simulator</b> setzt dich ans Ruder eines Kiesschiffs, das von einem Kite gezogen wird. Die Physik ist glaubwürdig: Zugkraft im Windfenster, scheinbarer Wind, Trägheit eines beladenen Schiffs, Böen und Stürme.</p><ul><li><b>Verstehen</b>, wie ein Kite ein Schiff zieht und warum er Achten fliegen muss.</li><li><b>Sehen</b>, dass langsamer fahren (Slow Steaming) der wichtigste Hebel gegen Emissionen bleibt, und was der Wind beiträgt.</li><li><b>Gegeneinander antreten</b> auf derselben Überfahrt, mit demselben Wetter für alle, und Zeiten im Team vergleichen.</li></ul>",
  card_sandbox_tag: "Verstehen · ohne Zeit", card_sandbox_desc: "Das Schiff von der Seite: Geschwindigkeit, Kurs und Wind einstellen und sehen, woher die Treibstoffersparnis kommt. Slow Steaming einfach erklärt.",
  card_beginner_tag: "≈ 1 Min. · Jugendliche und alle", card_beginner_desc: "Steuere das Schiff (WASD/ZQSD oder Maus), setze den Kite im richtigen Moment und erwische die Böen. Der Kite fliegt seine Achten von selbst: du wählst die Route.",
  card_expert_tag: "≈ 3 Min. · Ingenieure", card_expert_desc: "Fliege den Kite selbst mit den Pfeiltasten: hintere Leinen zum Lenken, vordere Leinen zum Fieren oder Dichtholen. Spiele mit den Grenzen des Windfensters.",
  hud_ship: "Schiff", hud_true_wind: "Wahrer Wind", hud_app_wind: "Scheinbarer Wind", hud_kite_pull: "Kite-Zug",
  top_view: "02 Draufsicht", leg_heading: "Kurs", leg_true: "Wahrer Wind", leg_app: "Scheinbarer Wind", leg_kite: "Kite-Zug",
  gains_title: "03 Ersparnis <b>vs 8 kn ohne Kite</b>", g_fuel: "Treibstoff", g_co2: "CO₂ vermieden", g_kite: "Kite-Schub",
  k_fuel: "Diesel / Überfahrt", k_co2: "CO₂ / Überfahrt", k_time: "Dauer", k_power: "Leistung",
  controls_title: "04 Steuerung <b>· Drehregler, Tastatur oder Mausrad</b>", kite_deployed: "Kite gesetzt", to_toggle: "zum Umschalten",
  preset_ref: "Referenz", preset_slow: "Slow Steaming", preset_ideal: "Idealer Wind", preset_storm: "Bise von vorn",
  ana_where: "05 Woher die Ersparnis kommt", ana_emissions: "Emissionen · 100 % = Referenz", ana_split: "Anteile am Gewinn", ana_curve: "06 CO₂ pro Überfahrt nach Geschwindigkeit", ana_cube: "07 Kubisches Gesetz",
  cube_note: "Leistung ∝ V³: Diesel pro Überfahrt (nur Rumpf, ohne Wind).",
  kn_speed: "Geschwindigkeit", kn_heading: "Kurs", kn_winddir: "Wind aus", kn_windspeed: "Windstärke",
  mission_n: "Mission {n}/{m}", m_toast: "Mission {n} geschafft ✓", m_done: "✓ Geschafft", m_already: "Bereits geschafft", m_running: "Läuft",
  m1_title: "Nur der Kite", m1_text: "Ohne langsamer zu fahren (≥ 7,9 Knoten) Kurs und Wind so wählen, dass der Kite mindestens 15 % CO₂ einspart.",
  m2_title: "Langsamer fahren", m2_text: "Gleiches Wetter, weniger Tempo: halbiere die Emissionen der Überfahrt (≥ 50 % CO₂ vermieden).",
  m3_title: "Bise von vorn", m3_text: "22 Knoten Gegenwind: der Kite nützt nichts. Finde trotzdem 30 % Ersparnis.",
  m4_title: "Der richtige Kompromiss", m4_text: "Erreiche Genf in unter 6 h und vermeide mindestens 55 % CO₂: kombiniere Tempo, Kurs und Wind.",
  delta_ref: "= Referenz", st_flying: "Kite fliegt · Flugbahn in Achten", st_off: "Kite geborgen", st_calm: "Kite ruht · zu wenig Wind", st_storm: "Kite geborgen · zu viel Wind", st_headwind: "Kite nutzlos · Gegenwind",
  st_off_short: "Kite geborgen", st_calm_short: "zu wenig Wind", st_storm_short: "zu viel Wind", st_headwind_short: "Gegenwind",
  big_zero: "0 % CO₂", big_less: "−{p} % CO₂", big_more: "+{p} % CO₂", sub_saved: "{t} kg vermieden von {r} kg", sub_more: "{t} kg mehr von {r} kg",
  seg_emitted: "{p} % ausgestossen", seg_speed: "−{p} % Tempo", seg_kite: "−{p} % Kite", rest_emitted: "{t} kg ausgestossen", share_speed: "Tempo {p} %", share_kite: "Kite {p} %", split_txt: "{s} % Tempo · {k} % Kite", no_gain: "keine Ersparnis",
  ins_faster: "<b>Schneller als die Referenz.</b> Die Leistung wächst mit der <b>dritten Potenz</b> der Geschwindigkeit: +{p} % Leistung für +{v} % Tempo.",
  ins_nogain: "<b>Noch keine Ersparnis.</b> Zwei Hebel: <b>langsamer fahren</b> (wirkt immer) oder <b>Rückenwind</b> für den Kite suchen.",
  ins_main: "<b>{s} % der Ersparnis kommen vom Langsamerfahren</b>, {k} % vom Kite. ",
  ins_speed_main: "Bei {v} kn liefert der Motor {p} % der Referenzleistung; jeder Kilometer kostet {f} % des Diesels.",
  ins_not_slowed: "Du bist noch nicht langsamer gefahren: bei 6–7 Knoten wäre die Ersparnis viel grösser, und zwar <b>garantiert</b>, bei jedem Wetter.",
  ins_wind_fav: "Sehr günstiger Wind … aber diese Ersparnis hängt vom Wetter ab, die vom Langsamerfahren ist <b>garantiert</b>.",
  ins_kite_none: "Der Kite bringt hier nichts: alles kommt vom Langsamerfahren.",
  g1_sub: "{t} kg Diesel {dir}", less: "weniger", more: "mehr", g2_sub: "≈ {n} km mit dem Auto", g3_sub: "{p} % des Schubs",
  c_ref: "Referenz", c_nokite: "ohne Kite", c_kite: "mit Kite", c_gain: "Kite-Beitrag",
  d_time: "Zeit", d_progress: "Fortschritt", d_speed: "Tempo", d_engine: "Motor", d_wind: "Wind", d_kite: "Kite", d_kite_bar: "Kite Zug · nutzbar", rig_area: "Fläche", rig_line: "Leinen", rig_locked: "Hole den Kite ein, um Fläche oder Leinen zu wechseln", e_rig: "Rigg", d_share: "Kite-Anteil", d_perf: "Flüssigkeit", d_avoided: "vermieden", d_gust: "Bö", d_storm: "Sturm", d_co2: "CO₂ ausgestossen", d_saved: "CO₂ vermieden (Kite)", d_heel: "Krängung", d_pen: "Strafzeiten",
  start_name: "VILLENEUVE", finish_name: "GENF", t_ghost: "Top-3-Spuren", t_window: "Fenster", throttle: "Gas", helm: "Ruder", kite: "Kite",
  kb_tension: "Zug", kb_trim: "Leistung", kb_zone: "Zone", kite_deploy: "Kite setzen", kite_retract: "Kite bergen",
  ks_stowed: "geborgen", ks_calm: "Flaute", ks_headwind: "Gegenwind", ks_launch: "startet", ks_crashed: "im Wasser",
  view_third: "Verfolger", view_cabin: "Steuerhaus", go: "Los!",
  name_eyebrow: "{mode} · Villeneuve → Genf", name_title: "Wer steht am <em>Ruder</em>?", name_intro: "Dein Spielername und dein Team erscheinen in den Ranglisten aller Spieler.",
  pseudo: "Spielername", pseudo_ph: "Dein Name", team: "Team", team_new_name: "Name des neuen Teams", team_ph: "z. B. Die Möwen",
  team_none: "— Kein Team —", team_members: "{t} · {n} Mitglied(er)", team_create: "＋ Neues Team erstellen …", err_name: "Gib einen Namen ein, um deine Zeit zu speichern.", err_team: "Gib deinem neuen Team einen Namen (oder wähle « Kein Team »).",
  pause_title: "Alles <em>angehalten</em>", pause_text: "Drücke <kbd>P</kbd> oder <kbd>Esc</kbd>, um weiterzuspielen.",
  race_abandoned: "Überfahrt abgebrochen",
  w_vaudaire: "Die Vaudaire weht aus Südost: Rückenwind, setze den Kite!", w_vent: "Der südwestliche « Vent » kommt von vorn: der Kite zieht wenig, halte das Tempo mit dem Motor.",
  w_joran: "Joran-Bö! Der Nordwestwind frischt schlagartig auf.", w_bise: "Die Bise aus Nordost schiebt dich nach Genf: jetzt die Böen erwischen.",
  storm_warn: "⚠ Joran-Sturm voraus: berge den Kite (Leertaste), wenn der Zug steigt!", storm_warn_expert: "⚠ Joran-Sturm: fiere die vorderen Leinen (↑) und verlasse die Powerzone.",
  dolphins: "🐬 Delfine begleiten dich!", gust_caught: "Bö erwischt! 💨",
  ev_kite_torn: "💥 Bö zu stark: der Kite ist beschädigt", ev_line_break: "💥 Überlast: die Leine ist gerissen", ev_kite_water: "🌊 Der Kite ist ins Wasser gestürzt",
  ev_aground: "Auf Grund gelaufen!", ev_cgn: "💥 Kollision mit einem CGN-Raddampfer", ev_jetski: "Zusammenstoss mit einem Jetski",
  kite_damaged_wait: "Kite wird repariert, ein paar Sekunden Geduld …", kite_out: "Kite gesetzt 🪁", kite_in: "Kite geborgen",
  overload: "ÜBERLAST", overload_hint: "berge den Kite (Leertaste), bevor er reisst", overload_hint_expert: "fiere (↑) oder verlasse die Powerzone",
  no_ghosts: "Noch keine Spuren: sei der Erste!",
  start_tip: "WASD/ZQSD oder Pfeile zum Steuern, Leertaste für den Kite. Kurs auf Genf!", start_tip_expert: "WASD/ZQSD für das Schiff, Pfeile für den Kite: fliege Achten in der Powerzone.",
  finish_toast: "Ziel am Jet d'eau! {t}",
  win_power: "POWERZONE", win_edge: "RAND", win_zenith: "ZENIT",
  boards: "Ranglisten", src_remote: "alle Spieler", src_local: "dieser Browser", p_day: "Heute", p_week: "Diese Woche", p_all: "Ewig", g_players: "Spieler", g_teams: "Teams",
  best_time: "Bestzeit", runs: "Fahrten", avg_time: "Mittlere Zeit", members: "Mitglieder", no_scores: "Noch keine Zeiten: sei der Erste!", no_teams: "Noch keine Teams.",
  runs_count: "{n} Fahrt(en) · Bestzeit jedes Spielers", team_rule: "Teamzeit = Mittel der Bestzeiten seiner Mitglieder", dist_note: "Verteilung der Bestzeiten", dist_empty: "Noch zu wenige Spieler", you: "du",
  end_eyebrow: "Ziel · {mode}", end_title_1: "Neuer <em>Rekord</em>! 🏆", end_title_podium: "Auf dem <em>Podest</em>! 🥇", end_title: "Im Ziel am <em>Jet d'eau</em>",
  e_time: "Fahrzeit", e_pen: "Strafzeiten", e_coll: "Kollision(en)", e_co2: "CO₂ des Motors", e_saved: "CO₂ dank Kite vermieden", end_rank: "Rang {r} von {n} Spielern (ewig)", speed_scale: "Tempo entlang deiner Route",
  read_title: "Was du <em>auf dem Bildschirm</em> siehst",
  hs_title: "Sandkasten: frei <em>entdecken</em>", hs_text: "Das Schiff wird von der Seite gezeigt. Stelle Tempo, Kurs und Wind ein und sieh, woher die Ersparnis kommt: meist bringt das Langsamerfahren etwa zwei Drittel, der Kite den Rest.",
  k_sb_speed: "Tempo ±0,5 Knoten", k_sb_heading: "Kurs ±5°", k_sb_kite: "Kite setzen / bergen", k_sb_knobs: "Drehregler drehen (ziehen oder Mausrad)",
  rs_hud: "<b>Oben</b>: Tempo und Kurs, wahrer Wind, scheinbarer Wind, Kite-Zug.", rs_mission: "<b>Mission</b> (unten rechts): ein Ziel, das grün wird, sobald es erreicht ist.",
  rs_compass: "<b>02 Kompass</b>: Kurs (grün), wahrer Wind (blau), scheinbarer Wind (gestrichelt), Kite-Zug (orange).", rs_gauges: "<b>03 Anzeigen</b>: gesparter Diesel und CO₂ gegenüber der Referenz (8 Knoten, ohne Kite).",
  rs_bars: "<b>05 Balken</b>: welcher Anteil vom Langsamerfahren und welcher vom Kite kommt.", rs_curves: "<b>06–07</b>: CO₂ pro Überfahrt nach Tempo und das kubische Gesetz.",
  hb_title: "Überquere den Genfersee <em>so schnell wie möglich</em>", hb_text: "Start am Kiesquai von Villeneuve, Ziel am Fuss des Jet d'eau in Genf. Deine Zeit wird auf die Millisekunde gemessen: jede Bö zählt!",
  hb_r1_t: "Ziel", hb_r1_d: "Die beste Zeit. Kollisionen (CGN-Dampfer +5 s, Jetskis +2 s, Ufer +1,5 s) werden addiert.",
  hb_r2_t: "Der Kite", hb_r2_d: "Er fliegt seine Achten selbst. Setze ihn bei Wind von hinten oder von der Seite und jage die Böen (dunkle Flecken).",
  hb_r3_t: "Gefahr", hb_r3_d: "Der Joran frischt mitten auf dem See plötzlich auf: berge den Kite, wenn der Zug rot wird, sonst reisst er (+4 s).",
  he_title: "Fliege den Kite <em>wie ein Profi</em>", he_text: "Gleiche Überfahrt, aber du fliegst den Schirm. Er bewegt sich selbstständig im Windfenster; du lenkst ihn und regelst seine Leistung. Wähle vor dem Start Fläche (10, 25 oder 100 m²) und Leinen (25, 100 oder 300 m): klein = wendig aber schwach, gross = kräftig aber träge; lange Leinen = mehr Wind in der Höhe, langsamere Kurven.",
  he_r1_t: "Windfenster", he_r1_d: "Mitte und tief: maximale Leistung. Rand und Zenit: fast nichts. In Achten erzeugt der Schirm seinen eigenen Wind und zieht viel stärker.",
  he_r2_t: "Vordere Leinen", he_r2_d: "↑ fieren = weniger Leistung, ↓ dichtholen = mehr Leistung. Zu viel Zug und die Leine reisst (+3 s): die Grenze hängt von der Kitegrösse ab.",
  he_r3_t: "Hintere Leinen", he_r3_d: "← → lenken den Schirm. Schnell fliegend dreht er schneller. Berührt er das Wasser: +2 s und Neustart.",
  ctrl_title: "Steuerung", k_throttle: "Gas: schneller / langsamer (bleibt stehen)", k_helm: "Ruder: Backbord / Steuerbord", k_kite_steer: "Kite: links / rechts lenken (hintere Leinen)",
  k_kite_trim: "Kite: ↑ fieren / ↓ dichtholen (vordere Leinen)", k_arrows_boat: "Die Pfeiltasten steuern auch das Schiff", k_kite_toggle: "Kite setzen / bergen", k_view: "Verfolger- / Steuerhausansicht", k_window: "Windfenster anzeigen",
  k_ghost: "Spuren der 3 besten Spieler", k_help: "Hilfe anzeigen", k_pause: "Pause",
  ctrl_mouse: "Mit der Maus: Gashebel links in der Szene, Ruderbalken unten (Doppelklick zum Zentrieren), Kite-Knopf unten rechts.",
  ctrl_qwerty: "AZERTY-Tastaturen: Z Q S D funktionieren auch.",
  rr_hud: "<b>Oben links</b>: Zeit, Tempo, Wind (Stärke und Richtung), nutzbarer Kite-Schub.", rr_progress: "<b>Oben Mitte</b>: Fortschritt von Villeneuve nach Genf.",
  rr_minimap: "<b>Minikarte</b>: deine Position, Böen (farbige Punkte), Sturmzone (rot) und CGN-Dampfer (weisse Punkte).",
  rr_wind: "<b>Striche auf dem Wasser</b>: der Wind, von blau (schwach) bis rot und violett (stark); dunkle Flecken = Böen, glatte Flächen = Flaute.",
  rr_kitebox: "<b>Kite-Box</b>: Leinenzug (rot = Gefahr), Zone im Windfenster, eingestellte Leistung.", rr_databar: "<b>Untere Leiste</b>: Motor, CO₂ ausgestossen und vermieden, Krängung, Strafzeiten, Bilder pro Sekunde.",
  rr_beginner: "Tipp: Mit dem Motor allein sind etwa 8,5 Knoten drin; ein gut platzierter Kite bringt 2 bis 4 mehr.", rr_expert: "Tipp: Genau in der Mitte bei voller Leistung reisst die Leine schnell. Spiele mit dem Fensterrand und fiere in den Böen."
});
